### PR TITLE
Fix #237, where code blocks are missing their source code

### LINKED ISSUE #237: Where code blocks are missing their source code
This is a problem because certain data table entries will become unreadable when turned into 
reports because `toString()` often distorts their representation.

Consider the following example:
```groovy

    def 'My API will throw exceptions if used incorrectly.'(
            Class<Exception> type, Consumer<MyThing > errorCode
    ) {
        given :
        MyThing t  = new MyThing()

        when :
        errorCode(t)

        then :
        var exception = thrown(type)
        and :
        exception.message != "" && exception.message.length() > 13

        where :
        type                          | errorCode
        IllegalArgumentException      | { MyThing x -> x.onlyPositive(-1)                }
        NullPointerException          | { MyThing x -> x.dontLikeNull(null)              }
        UnsupportedOperationException | { MyThing x -> x.workInProgress("do something")  }
        Exception                     | { MyThing x -> x.iDontWork_ever()                }
    }
```
So when I try to make this into living documentation using the data table entries
using the `dataValues` in my template file:
```groovy
features.eachFeature { name, result, blocks, iterations, params ->
    params.each { p -> /* build table header */ }
    iterations.each { iteration -> iteration.dataValues /*do data row*/ }
}
```
I get something like this:

| **exception**                 | **errorCode**                                        |
|-------------------------------|------------------------------------------------------|
| IllegalArgumentException      | This_Spec$__spock_feature_0_1prov1_closure1@7f9aae2e |
| NullPointerException          | This_Spec$__spock_feature_0_1prov1_closure2@780c3492 |
| UnsupportedOperationException | This_Spec$__spock_feature_0_1prov1_closure3@7cf0a48b |
| Exception                     | This_Spec$__spock_feature_0_1prov1_closure4@7c36cc9b |

However, what I really want is this:

  | **exception**                 | **errorCode**                                        |
  |-------------------------------|------------------------------------------------------|
  | IllegalArgumentException      | { MyThing x -> x.onlyPositive(-1)                }   |
  | NullPointerException          | { MyThing x -> x.dontLikeNull(null)              }   |
  | UnsupportedOperationException | { MyThing x -> x.workInProgress("do something")  }   |
  | Exception                     | { MyThing x -> x.iDontWork_ever()                }   |

I understand that this is not what the `dataValues` is for, what I would expect is
that there is the actual code of the `where` block in the `block.sourceCode` field,
but it is always missing!
After looking into the code I noticed that there is a simple condition preventing the 
where block code from being read, I removed it and it worked perfectly well.

I would be happy to fix this if that's okay, this would not change anything except
it would open up more option for users.
This is particularly interesting to me since we are using this plugin to generate 
test suite browsers for pure documentation purposes so that newcomers can learn how to
use our libraries and APIs without having to dig through the source code files...

### PR DESCRIPTION
**Pull request by Gleethos**
Skipping the `where` blocks altogether in the existing generators as you suggested did not fix the
test regressions because they were still used to build the data tables, instead I only
had to ignore the code statements from being iterated over.
But I believe these changes are as minimal and clean as possible.

### CODE REVIEW

**Comment by renatoathaydes** [comment]
Excellent @Gleethos .

Can your rebase this on the dev branch? If that's too much, that's fine, I can backport it.

File: src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy [hunk 1]
```diff
@@ -96,7 +96,7 @@ class VividAstInspectorSpec extends Specification {
         blocks[ 1 ].statements.isEmpty()
         blocks[ 2 ].statements.isEmpty()
         blocks[ 3 ].statements == [ 'x == y' ]
-        blocks[ 4 ].statements.isEmpty() // where statements are not captured
+        blocks[ 4 ].statements == [ "x | y", "'a' | 'a'", "'b' | 'c'" ]
```
Comment (renatoathaydes) [inline src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy:99]: So, the lines with the examples do not get captured, right? Wasn't that what you wanted to have?

File: src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy [hunk 2]
```diff
@@ -177,10 +177,6 @@ class VividASTVisitor extends ClassCodeVisitorSupport {
                 }
 
                 codeCollector.add( statement )
-
-                if ( statement.statementLabel == 'where' ) {
-                    waitForNextBlock = true
```
Comment (renatoathaydes) [inline src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy:182]: I wonder if this boolean can be removed now? This code was contributed by someone else, I don't remember why this was needed.

File: src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy (hunk 1 above)
Comment (renatoathaydes) [reply src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy:99]: Ah! Sorry, looked too fast... those `a` and `b`s ARE THE EXAMPLES :D!?

**Review by renatoathaydes — APPROVED** [review]

File: src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy (hunk 2 above)
Comment (Gleethos) [reply src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy:182]: Also, all of the tests still run green.

File: src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy (hunk 1 above)
Comment (Gleethos) [reply src/test/groovy/com/athaydes/spockframework/report/internal/VividAstInspectorSpec.groovy:99]: Yes this is exactly what I was describing in the issue.
The entire `where` source code block is available as a list of statements exactly like 
all the other code blocks. 🥳 

Although, now that I look at this again: 
Correct me if I am wrong, but could it be that there is an indent missing in the header of the table?
Should `"x | y"` not be `"  x | y"`?
Because otherwise the `|` lines might not match? 🤔

File: src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy (hunk 2 above)
Comment (renatoathaydes) [reply src/main/groovy/com/athaydes/spockframework/report/vivid/VividAstInspector.groovy:182]: I am a bit busy at the moment... will get to this in the next few days.
